### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mattrighetti** [LukeMathWalker/LukeMathWalker#1]
https://github.com/LukeMathWalker/LukeMathWalker/blob/2b7643f21c3cc95b08babf532ae930a9fe159d8f/README.md?plain=1#L27

It's now [`tracing-bunyan-formatter`](https://github.com/LukeMathWalker/tracing-bunyan-formatter) :)

**Comment by LukeMathWalker** [comment]
Fixed, thanks!
